// Code generated by entc, DO NOT EDIT.

package schema

import (
	"context"
	"errors"
	"fmt"
	"orginone/common/schema/asmarketapp"
	"orginone/common/schema/asredeploydata"
	"orginone/common/tools/date"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AsRedeployDataCreate is the builder for creating a AsRedeployData entity.
type AsRedeployDataCreate struct {
	config
	mutation *AsRedeployDataMutation
	hooks    []Hook
}

// SetAppID sets the "app_id" field.
func (ardc *AsRedeployDataCreate) SetAppID(i int64) *AsRedeployDataCreate {
	ardc.mutation.SetAppID(i)
	return ardc
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableAppID(i *int64) *AsRedeployDataCreate {
	if i != nil {
		ardc.SetAppID(*i)
	}
	return ardc
}

// SetApplication sets the "application" field.
func (ardc *AsRedeployDataCreate) SetApplication(s string) *AsRedeployDataCreate {
	ardc.mutation.SetApplication(s)
	return ardc
}

// SetNillableApplication sets the "application" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableApplication(s *string) *AsRedeployDataCreate {
	if s != nil {
		ardc.SetApplication(*s)
	}
	return ardc
}

// SetIsDeleted sets the "is_deleted" field.
func (ardc *AsRedeployDataCreate) SetIsDeleted(i int64) *AsRedeployDataCreate {
	ardc.mutation.SetIsDeleted(i)
	return ardc
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableIsDeleted(i *int64) *AsRedeployDataCreate {
	if i != nil {
		ardc.SetIsDeleted(*i)
	}
	return ardc
}

// SetStatus sets the "status" field.
func (ardc *AsRedeployDataCreate) SetStatus(i int64) *AsRedeployDataCreate {
	ardc.mutation.SetStatus(i)
	return ardc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableStatus(i *int64) *AsRedeployDataCreate {
	if i != nil {
		ardc.SetStatus(*i)
	}
	return ardc
}

// SetCreateUser sets the "create_user" field.
func (ardc *AsRedeployDataCreate) SetCreateUser(i int64) *AsRedeployDataCreate {
	ardc.mutation.SetCreateUser(i)
	return ardc
}

// SetNillableCreateUser sets the "create_user" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableCreateUser(i *int64) *AsRedeployDataCreate {
	if i != nil {
		ardc.SetCreateUser(*i)
	}
	return ardc
}

// SetUpdateUser sets the "update_user" field.
func (ardc *AsRedeployDataCreate) SetUpdateUser(i int64) *AsRedeployDataCreate {
	ardc.mutation.SetUpdateUser(i)
	return ardc
}

// SetNillableUpdateUser sets the "update_user" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableUpdateUser(i *int64) *AsRedeployDataCreate {
	if i != nil {
		ardc.SetUpdateUser(*i)
	}
	return ardc
}

// SetCreateTime sets the "create_time" field.
func (ardc *AsRedeployDataCreate) SetCreateTime(dt date.DateTime) *AsRedeployDataCreate {
	ardc.mutation.SetCreateTime(dt)
	return ardc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableCreateTime(dt *date.DateTime) *AsRedeployDataCreate {
	if dt != nil {
		ardc.SetCreateTime(*dt)
	}
	return ardc
}

// SetUpdateTime sets the "update_time" field.
func (ardc *AsRedeployDataCreate) SetUpdateTime(dt date.DateTime) *AsRedeployDataCreate {
	ardc.mutation.SetUpdateTime(dt)
	return ardc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableUpdateTime(dt *date.DateTime) *AsRedeployDataCreate {
	if dt != nil {
		ardc.SetUpdateTime(*dt)
	}
	return ardc
}

// SetID sets the "id" field.
func (ardc *AsRedeployDataCreate) SetID(i int64) *AsRedeployDataCreate {
	ardc.mutation.SetID(i)
	return ardc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableID(i *int64) *AsRedeployDataCreate {
	if i != nil {
		ardc.SetID(*i)
	}
	return ardc
}

// SetAppxID sets the "appx" edge to the AsMarketApp entity by ID.
func (ardc *AsRedeployDataCreate) SetAppxID(id int64) *AsRedeployDataCreate {
	ardc.mutation.SetAppxID(id)
	return ardc
}

// SetNillableAppxID sets the "appx" edge to the AsMarketApp entity by ID if the given value is not nil.
func (ardc *AsRedeployDataCreate) SetNillableAppxID(id *int64) *AsRedeployDataCreate {
	if id != nil {
		ardc = ardc.SetAppxID(*id)
	}
	return ardc
}

// SetAppx sets the "appx" edge to the AsMarketApp entity.
func (ardc *AsRedeployDataCreate) SetAppx(a *AsMarketApp) *AsRedeployDataCreate {
	return ardc.SetAppxID(a.ID)
}

// Mutation returns the AsRedeployDataMutation object of the builder.
func (ardc *AsRedeployDataCreate) Mutation() *AsRedeployDataMutation {
	return ardc.mutation
}

// Save creates the AsRedeployData in the database.
func (ardc *AsRedeployDataCreate) Save(ctx context.Context) (*AsRedeployData, error) {
	var (
		err  error
		node *AsRedeployData
	)
	ardc.defaults()
	if len(ardc.hooks) == 0 {
		if err = ardc.check(); err != nil {
			return nil, err
		}
		node, err = ardc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AsRedeployDataMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ardc.check(); err != nil {
				return nil, err
			}
			ardc.mutation = mutation
			if node, err = ardc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ardc.hooks) - 1; i >= 0; i-- {
			if ardc.hooks[i] == nil {
				return nil, fmt.Errorf("schema: uninitialized hook (forgotten import schema/runtime?)")
			}
			mut = ardc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ardc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ardc *AsRedeployDataCreate) SaveX(ctx context.Context) *AsRedeployData {
	v, err := ardc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ardc *AsRedeployDataCreate) Exec(ctx context.Context) error {
	_, err := ardc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ardc *AsRedeployDataCreate) ExecX(ctx context.Context) {
	if err := ardc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ardc *AsRedeployDataCreate) defaults() {
	if _, ok := ardc.mutation.IsDeleted(); !ok {
		v := asredeploydata.DefaultIsDeleted
		ardc.mutation.SetIsDeleted(v)
	}
	if _, ok := ardc.mutation.Status(); !ok {
		v := asredeploydata.DefaultStatus
		ardc.mutation.SetStatus(v)
	}
	if _, ok := ardc.mutation.CreateTime(); !ok {
		v := asredeploydata.DefaultCreateTime()
		ardc.mutation.SetCreateTime(v)
	}
	if _, ok := ardc.mutation.UpdateTime(); !ok {
		v := asredeploydata.DefaultUpdateTime()
		ardc.mutation.SetUpdateTime(v)
	}
	if _, ok := ardc.mutation.ID(); !ok {
		v := asredeploydata.DefaultID()
		ardc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ardc *AsRedeployDataCreate) check() error {
	if _, ok := ardc.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`schema: missing required field "AsRedeployData.is_deleted"`)}
	}
	return nil
}

func (ardc *AsRedeployDataCreate) sqlSave(ctx context.Context) (*AsRedeployData, error) {
	_node, _spec := ardc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ardc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (ardc *AsRedeployDataCreate) createSpec() (*AsRedeployData, *sqlgraph.CreateSpec) {
	var (
		_node = &AsRedeployData{config: ardc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: asredeploydata.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: asredeploydata.FieldID,
			},
		}
	)
	if id, ok := ardc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ardc.mutation.Application(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: asredeploydata.FieldApplication,
		})
		_node.Application = value
	}
	if value, ok := ardc.mutation.IsDeleted(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: asredeploydata.FieldIsDeleted,
		})
		_node.IsDeleted = value
	}
	if value, ok := ardc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: asredeploydata.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := ardc.mutation.CreateUser(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: asredeploydata.FieldCreateUser,
		})
		_node.CreateUser = value
	}
	if value, ok := ardc.mutation.UpdateUser(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: asredeploydata.FieldUpdateUser,
		})
		_node.UpdateUser = value
	}
	if value, ok := ardc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: asredeploydata.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := ardc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: asredeploydata.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if nodes := ardc.mutation.AppxIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   asredeploydata.AppxTable,
			Columns: []string{asredeploydata.AppxColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: asmarketapp.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AppID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AsRedeployDataCreateBulk is the builder for creating many AsRedeployData entities in bulk.
type AsRedeployDataCreateBulk struct {
	config
	builders []*AsRedeployDataCreate
}

// Save creates the AsRedeployData entities in the database.
func (ardcb *AsRedeployDataCreateBulk) Save(ctx context.Context) ([]*AsRedeployData, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ardcb.builders))
	nodes := make([]*AsRedeployData, len(ardcb.builders))
	mutators := make([]Mutator, len(ardcb.builders))
	for i := range ardcb.builders {
		func(i int, root context.Context) {
			builder := ardcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AsRedeployDataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ardcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ardcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ardcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ardcb *AsRedeployDataCreateBulk) SaveX(ctx context.Context) []*AsRedeployData {
	v, err := ardcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ardcb *AsRedeployDataCreateBulk) Exec(ctx context.Context) error {
	_, err := ardcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ardcb *AsRedeployDataCreateBulk) ExecX(ctx context.Context) {
	if err := ardcb.Exec(ctx); err != nil {
		panic(err)
	}
}
