// Code generated by entc, DO NOT EDIT.

package schema

import (
	"context"
	"errors"
	"fmt"
	"orginone/common/schema/astenanticon"
	"orginone/common/tools/date"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AsTenantIconCreate is the builder for creating a AsTenantIcon entity.
type AsTenantIconCreate struct {
	config
	mutation *AsTenantIconMutation
	hooks    []Hook
}

// SetTenantCode sets the "tenant_code" field.
func (atic *AsTenantIconCreate) SetTenantCode(s string) *AsTenantIconCreate {
	atic.mutation.SetTenantCode(s)
	return atic
}

// SetNillableTenantCode sets the "tenant_code" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableTenantCode(s *string) *AsTenantIconCreate {
	if s != nil {
		atic.SetTenantCode(*s)
	}
	return atic
}

// SetIcon sets the "icon" field.
func (atic *AsTenantIconCreate) SetIcon(s string) *AsTenantIconCreate {
	atic.mutation.SetIcon(s)
	return atic
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableIcon(s *string) *AsTenantIconCreate {
	if s != nil {
		atic.SetIcon(*s)
	}
	return atic
}

// SetIsDeleted sets the "is_deleted" field.
func (atic *AsTenantIconCreate) SetIsDeleted(i int64) *AsTenantIconCreate {
	atic.mutation.SetIsDeleted(i)
	return atic
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableIsDeleted(i *int64) *AsTenantIconCreate {
	if i != nil {
		atic.SetIsDeleted(*i)
	}
	return atic
}

// SetStatus sets the "status" field.
func (atic *AsTenantIconCreate) SetStatus(i int64) *AsTenantIconCreate {
	atic.mutation.SetStatus(i)
	return atic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableStatus(i *int64) *AsTenantIconCreate {
	if i != nil {
		atic.SetStatus(*i)
	}
	return atic
}

// SetCreateUser sets the "create_user" field.
func (atic *AsTenantIconCreate) SetCreateUser(i int64) *AsTenantIconCreate {
	atic.mutation.SetCreateUser(i)
	return atic
}

// SetNillableCreateUser sets the "create_user" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableCreateUser(i *int64) *AsTenantIconCreate {
	if i != nil {
		atic.SetCreateUser(*i)
	}
	return atic
}

// SetUpdateUser sets the "update_user" field.
func (atic *AsTenantIconCreate) SetUpdateUser(i int64) *AsTenantIconCreate {
	atic.mutation.SetUpdateUser(i)
	return atic
}

// SetNillableUpdateUser sets the "update_user" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableUpdateUser(i *int64) *AsTenantIconCreate {
	if i != nil {
		atic.SetUpdateUser(*i)
	}
	return atic
}

// SetCreateTime sets the "create_time" field.
func (atic *AsTenantIconCreate) SetCreateTime(dt date.DateTime) *AsTenantIconCreate {
	atic.mutation.SetCreateTime(dt)
	return atic
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableCreateTime(dt *date.DateTime) *AsTenantIconCreate {
	if dt != nil {
		atic.SetCreateTime(*dt)
	}
	return atic
}

// SetUpdateTime sets the "update_time" field.
func (atic *AsTenantIconCreate) SetUpdateTime(dt date.DateTime) *AsTenantIconCreate {
	atic.mutation.SetUpdateTime(dt)
	return atic
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableUpdateTime(dt *date.DateTime) *AsTenantIconCreate {
	if dt != nil {
		atic.SetUpdateTime(*dt)
	}
	return atic
}

// SetID sets the "id" field.
func (atic *AsTenantIconCreate) SetID(i int64) *AsTenantIconCreate {
	atic.mutation.SetID(i)
	return atic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (atic *AsTenantIconCreate) SetNillableID(i *int64) *AsTenantIconCreate {
	if i != nil {
		atic.SetID(*i)
	}
	return atic
}

// Mutation returns the AsTenantIconMutation object of the builder.
func (atic *AsTenantIconCreate) Mutation() *AsTenantIconMutation {
	return atic.mutation
}

// Save creates the AsTenantIcon in the database.
func (atic *AsTenantIconCreate) Save(ctx context.Context) (*AsTenantIcon, error) {
	var (
		err  error
		node *AsTenantIcon
	)
	atic.defaults()
	if len(atic.hooks) == 0 {
		if err = atic.check(); err != nil {
			return nil, err
		}
		node, err = atic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AsTenantIconMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = atic.check(); err != nil {
				return nil, err
			}
			atic.mutation = mutation
			if node, err = atic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(atic.hooks) - 1; i >= 0; i-- {
			if atic.hooks[i] == nil {
				return nil, fmt.Errorf("schema: uninitialized hook (forgotten import schema/runtime?)")
			}
			mut = atic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, atic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (atic *AsTenantIconCreate) SaveX(ctx context.Context) *AsTenantIcon {
	v, err := atic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atic *AsTenantIconCreate) Exec(ctx context.Context) error {
	_, err := atic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atic *AsTenantIconCreate) ExecX(ctx context.Context) {
	if err := atic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (atic *AsTenantIconCreate) defaults() {
	if _, ok := atic.mutation.IsDeleted(); !ok {
		v := astenanticon.DefaultIsDeleted
		atic.mutation.SetIsDeleted(v)
	}
	if _, ok := atic.mutation.Status(); !ok {
		v := astenanticon.DefaultStatus
		atic.mutation.SetStatus(v)
	}
	if _, ok := atic.mutation.CreateTime(); !ok {
		v := astenanticon.DefaultCreateTime()
		atic.mutation.SetCreateTime(v)
	}
	if _, ok := atic.mutation.UpdateTime(); !ok {
		v := astenanticon.DefaultUpdateTime()
		atic.mutation.SetUpdateTime(v)
	}
	if _, ok := atic.mutation.ID(); !ok {
		v := astenanticon.DefaultID()
		atic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atic *AsTenantIconCreate) check() error {
	if _, ok := atic.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`schema: missing required field "AsTenantIcon.is_deleted"`)}
	}
	return nil
}

func (atic *AsTenantIconCreate) sqlSave(ctx context.Context) (*AsTenantIcon, error) {
	_node, _spec := atic.createSpec()
	if err := sqlgraph.CreateNode(ctx, atic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (atic *AsTenantIconCreate) createSpec() (*AsTenantIcon, *sqlgraph.CreateSpec) {
	var (
		_node = &AsTenantIcon{config: atic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: astenanticon.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: astenanticon.FieldID,
			},
		}
	)
	if id, ok := atic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := atic.mutation.TenantCode(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: astenanticon.FieldTenantCode,
		})
		_node.TenantCode = value
	}
	if value, ok := atic.mutation.Icon(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: astenanticon.FieldIcon,
		})
		_node.Icon = value
	}
	if value, ok := atic.mutation.IsDeleted(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: astenanticon.FieldIsDeleted,
		})
		_node.IsDeleted = value
	}
	if value, ok := atic.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: astenanticon.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := atic.mutation.CreateUser(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: astenanticon.FieldCreateUser,
		})
		_node.CreateUser = value
	}
	if value, ok := atic.mutation.UpdateUser(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: astenanticon.FieldUpdateUser,
		})
		_node.UpdateUser = value
	}
	if value, ok := atic.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: astenanticon.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := atic.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: astenanticon.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	return _node, _spec
}

// AsTenantIconCreateBulk is the builder for creating many AsTenantIcon entities in bulk.
type AsTenantIconCreateBulk struct {
	config
	builders []*AsTenantIconCreate
}

// Save creates the AsTenantIcon entities in the database.
func (aticb *AsTenantIconCreateBulk) Save(ctx context.Context) ([]*AsTenantIcon, error) {
	specs := make([]*sqlgraph.CreateSpec, len(aticb.builders))
	nodes := make([]*AsTenantIcon, len(aticb.builders))
	mutators := make([]Mutator, len(aticb.builders))
	for i := range aticb.builders {
		func(i int, root context.Context) {
			builder := aticb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AsTenantIconMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aticb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aticb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aticb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aticb *AsTenantIconCreateBulk) SaveX(ctx context.Context) []*AsTenantIcon {
	v, err := aticb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aticb *AsTenantIconCreateBulk) Exec(ctx context.Context) error {
	_, err := aticb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aticb *AsTenantIconCreateBulk) ExecX(ctx context.Context) {
	if err := aticb.Exec(ctx); err != nil {
		panic(err)
	}
}
