// Code generated by entc, DO NOT EDIT.

package schema

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"
	"orginone/common/schema/asinneragency"
	"orginone/common/schema/asjob"
	"orginone/common/schema/asmarketappusertemplate"
	"orginone/common/schema/asmarketmenuusersort"
	"orginone/common/schema/asmarketroledistribution"
	"orginone/common/schema/asmarketusedapp"
	"orginone/common/schema/asperson"
	"orginone/common/schema/asrole"
	"orginone/common/schema/asuser"
	"orginone/common/schema/asworkingdata"
	"orginone/common/schema/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AsUserQuery is the builder for querying AsUser entities.
type AsUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AsUser
	// eager-loading edges.
	withPerson            *AsPersonQuery
	withRoles             *AsRoleQuery
	withJobs              *AsJobQuery
	withUsedapps          *AsMarketUsedAppQuery
	withWorkingDatas      *AsWorkingDataQuery
	withAgencys           *AsInnerAgencyQuery
	withRoleDistribs      *AsMarketRoleDistributionQuery
	withAppMenusUserSorts *AsMarketMenuUserSortQuery
	withAppUserTemplates  *AsMarketAppUserTemplateQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AsUserQuery builder.
func (auq *AsUserQuery) Where(ps ...predicate.AsUser) *AsUserQuery {
	auq.predicates = append(auq.predicates, ps...)
	return auq
}

// Limit adds a limit step to the query.
func (auq *AsUserQuery) Limit(limit int) *AsUserQuery {
	auq.limit = &limit
	return auq
}

// Offset adds an offset step to the query.
func (auq *AsUserQuery) Offset(offset int) *AsUserQuery {
	auq.offset = &offset
	return auq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (auq *AsUserQuery) Unique(unique bool) *AsUserQuery {
	auq.unique = &unique
	return auq
}

// Order adds an order step to the query.
func (auq *AsUserQuery) Order(o ...OrderFunc) *AsUserQuery {
	auq.order = append(auq.order, o...)
	return auq
}

// QueryPerson chains the current query on the "person" edge.
func (auq *AsUserQuery) QueryPerson() *AsPersonQuery {
	query := &AsPersonQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asperson.Table, asperson.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, asuser.PersonTable, asuser.PersonColumn),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoles chains the current query on the "roles" edge.
func (auq *AsUserQuery) QueryRoles() *AsRoleQuery {
	query := &AsRoleQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asrole.Table, asrole.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, asuser.RolesTable, asuser.RolesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJobs chains the current query on the "jobs" edge.
func (auq *AsUserQuery) QueryJobs() *AsJobQuery {
	query := &AsJobQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asjob.Table, asjob.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, asuser.JobsTable, asuser.JobsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsedapps chains the current query on the "usedapps" edge.
func (auq *AsUserQuery) QueryUsedapps() *AsMarketUsedAppQuery {
	query := &AsMarketUsedAppQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asmarketusedapp.Table, asmarketusedapp.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, asuser.UsedappsTable, asuser.UsedappsColumn),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkingDatas chains the current query on the "workingDatas" edge.
func (auq *AsUserQuery) QueryWorkingDatas() *AsWorkingDataQuery {
	query := &AsWorkingDataQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asworkingdata.Table, asworkingdata.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, asuser.WorkingDatasTable, asuser.WorkingDatasColumn),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgencys chains the current query on the "agencys" edge.
func (auq *AsUserQuery) QueryAgencys() *AsInnerAgencyQuery {
	query := &AsInnerAgencyQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asinneragency.Table, asinneragency.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, asuser.AgencysTable, asuser.AgencysPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoleDistribs chains the current query on the "roleDistribs" edge.
func (auq *AsUserQuery) QueryRoleDistribs() *AsMarketRoleDistributionQuery {
	query := &AsMarketRoleDistributionQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asmarketroledistribution.Table, asmarketroledistribution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, asuser.RoleDistribsTable, asuser.RoleDistribsColumn),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAppMenusUserSorts chains the current query on the "appMenusUserSorts" edge.
func (auq *AsUserQuery) QueryAppMenusUserSorts() *AsMarketMenuUserSortQuery {
	query := &AsMarketMenuUserSortQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asmarketmenuusersort.Table, asmarketmenuusersort.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, asuser.AppMenusUserSortsTable, asuser.AppMenusUserSortsColumn),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAppUserTemplates chains the current query on the "appUserTemplates" edge.
func (auq *AsUserQuery) QueryAppUserTemplates() *AsMarketAppUserTemplateQuery {
	query := &AsMarketAppUserTemplateQuery{config: auq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := auq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(asuser.Table, asuser.FieldID, selector),
			sqlgraph.To(asmarketappusertemplate.Table, asmarketappusertemplate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, asuser.AppUserTemplatesTable, asuser.AppUserTemplatesColumn),
		)
		fromU = sqlgraph.SetNeighbors(auq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AsUser entity from the query.
// Returns a *NotFoundError when no AsUser was found.
func (auq *AsUserQuery) First(ctx context.Context) (*AsUser, error) {
	nodes, err := auq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{asuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (auq *AsUserQuery) FirstX(ctx context.Context) *AsUser {
	node, err := auq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AsUser ID from the query.
// Returns a *NotFoundError when no AsUser ID was found.
func (auq *AsUserQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = auq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{asuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (auq *AsUserQuery) FirstIDX(ctx context.Context) int64 {
	id, err := auq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AsUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AsUser entity is found.
// Returns a *NotFoundError when no AsUser entities are found.
func (auq *AsUserQuery) Only(ctx context.Context) (*AsUser, error) {
	nodes, err := auq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{asuser.Label}
	default:
		return nil, &NotSingularError{asuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (auq *AsUserQuery) OnlyX(ctx context.Context) *AsUser {
	node, err := auq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AsUser ID in the query.
// Returns a *NotSingularError when more than one AsUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (auq *AsUserQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = auq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = &NotSingularError{asuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (auq *AsUserQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := auq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AsUsers.
func (auq *AsUserQuery) All(ctx context.Context) ([]*AsUser, error) {
	if err := auq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return auq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (auq *AsUserQuery) AllX(ctx context.Context) []*AsUser {
	nodes, err := auq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AsUser IDs.
func (auq *AsUserQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := auq.Select(asuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (auq *AsUserQuery) IDsX(ctx context.Context) []int64 {
	ids, err := auq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (auq *AsUserQuery) Count(ctx context.Context) (int64, error) {
	if err := auq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return auq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (auq *AsUserQuery) CountX(ctx context.Context) int64 {
	count, err := auq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (auq *AsUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := auq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return auq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (auq *AsUserQuery) ExistX(ctx context.Context) bool {
	exist, err := auq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AsUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (auq *AsUserQuery) Clone() *AsUserQuery {
	if auq == nil {
		return nil
	}
	return &AsUserQuery{
		config:                auq.config,
		limit:                 auq.limit,
		offset:                auq.offset,
		order:                 append([]OrderFunc{}, auq.order...),
		predicates:            append([]predicate.AsUser{}, auq.predicates...),
		withPerson:            auq.withPerson.Clone(),
		withRoles:             auq.withRoles.Clone(),
		withJobs:              auq.withJobs.Clone(),
		withUsedapps:          auq.withUsedapps.Clone(),
		withWorkingDatas:      auq.withWorkingDatas.Clone(),
		withAgencys:           auq.withAgencys.Clone(),
		withRoleDistribs:      auq.withRoleDistribs.Clone(),
		withAppMenusUserSorts: auq.withAppMenusUserSorts.Clone(),
		withAppUserTemplates:  auq.withAppUserTemplates.Clone(),
		// clone intermediate query.
		sql:    auq.sql.Clone(),
		path:   auq.path,
		unique: auq.unique,
	}
}

// WithPerson tells the query-builder to eager-load the nodes that are connected to
// the "person" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithPerson(opts ...func(*AsPersonQuery)) *AsUserQuery {
	query := &AsPersonQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withPerson = query
	return auq
}

// WithRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithRoles(opts ...func(*AsRoleQuery)) *AsUserQuery {
	query := &AsRoleQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withRoles = query
	return auq
}

// WithJobs tells the query-builder to eager-load the nodes that are connected to
// the "jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithJobs(opts ...func(*AsJobQuery)) *AsUserQuery {
	query := &AsJobQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withJobs = query
	return auq
}

// WithUsedapps tells the query-builder to eager-load the nodes that are connected to
// the "usedapps" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithUsedapps(opts ...func(*AsMarketUsedAppQuery)) *AsUserQuery {
	query := &AsMarketUsedAppQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withUsedapps = query
	return auq
}

// WithWorkingDatas tells the query-builder to eager-load the nodes that are connected to
// the "workingDatas" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithWorkingDatas(opts ...func(*AsWorkingDataQuery)) *AsUserQuery {
	query := &AsWorkingDataQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withWorkingDatas = query
	return auq
}

// WithAgencys tells the query-builder to eager-load the nodes that are connected to
// the "agencys" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithAgencys(opts ...func(*AsInnerAgencyQuery)) *AsUserQuery {
	query := &AsInnerAgencyQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withAgencys = query
	return auq
}

// WithRoleDistribs tells the query-builder to eager-load the nodes that are connected to
// the "roleDistribs" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithRoleDistribs(opts ...func(*AsMarketRoleDistributionQuery)) *AsUserQuery {
	query := &AsMarketRoleDistributionQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withRoleDistribs = query
	return auq
}

// WithAppMenusUserSorts tells the query-builder to eager-load the nodes that are connected to
// the "appMenusUserSorts" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithAppMenusUserSorts(opts ...func(*AsMarketMenuUserSortQuery)) *AsUserQuery {
	query := &AsMarketMenuUserSortQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withAppMenusUserSorts = query
	return auq
}

// WithAppUserTemplates tells the query-builder to eager-load the nodes that are connected to
// the "appUserTemplates" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) WithAppUserTemplates(opts ...func(*AsMarketAppUserTemplateQuery)) *AsUserQuery {
	query := &AsMarketAppUserTemplateQuery{config: auq.config}
	for _, opt := range opts {
		opt(query)
	}
	auq.withAppUserTemplates = query
	return auq
}

// ThenPerson tells the query-builder to eager-load the nodes that are connected to
// the "person" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenPerson(opts ...func(*AsPersonQuery)) *AsUserQuery {
	query := &AsPersonQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asperson.IsDeleted(0)))
	}
	auq.withPerson = query
	return auq
}

// ThenRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenRoles(opts ...func(*AsRoleQuery)) *AsUserQuery {
	query := &AsRoleQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asrole.IsDeleted(0)))
	}
	auq.withRoles = query
	return auq
}

// ThenJobs tells the query-builder to eager-load the nodes that are connected to
// the "jobs" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenJobs(opts ...func(*AsJobQuery)) *AsUserQuery {
	query := &AsJobQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asjob.IsDeleted(0)))
	}
	auq.withJobs = query
	return auq
}

// ThenUsedapps tells the query-builder to eager-load the nodes that are connected to
// the "usedapps" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenUsedapps(opts ...func(*AsMarketUsedAppQuery)) *AsUserQuery {
	query := &AsMarketUsedAppQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asmarketusedapp.IsDeleted(0)))
	}
	auq.withUsedapps = query
	return auq
}

// ThenWorkingDatas tells the query-builder to eager-load the nodes that are connected to
// the "workingDatas" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenWorkingDatas(opts ...func(*AsWorkingDataQuery)) *AsUserQuery {
	query := &AsWorkingDataQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asworkingdata.IsDeleted(0)))
	}
	auq.withWorkingDatas = query
	return auq
}

// ThenAgencys tells the query-builder to eager-load the nodes that are connected to
// the "agencys" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenAgencys(opts ...func(*AsInnerAgencyQuery)) *AsUserQuery {
	query := &AsInnerAgencyQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asinneragency.IsDeleted(0)))
	}
	auq.withAgencys = query
	return auq
}

// ThenRoleDistribs tells the query-builder to eager-load the nodes that are connected to
// the "roleDistribs" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenRoleDistribs(opts ...func(*AsMarketRoleDistributionQuery)) *AsUserQuery {
	query := &AsMarketRoleDistributionQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asmarketroledistribution.IsDeleted(0)))
	}
	auq.withRoleDistribs = query
	return auq
}

// ThenAppMenusUserSorts tells the query-builder to eager-load the nodes that are connected to
// the "appMenusUserSorts" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenAppMenusUserSorts(opts ...func(*AsMarketMenuUserSortQuery)) *AsUserQuery {
	query := &AsMarketMenuUserSortQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asmarketmenuusersort.IsDeleted(0)))
	}
	auq.withAppMenusUserSorts = query
	return auq
}

// ThenAppUserTemplates tells the query-builder to eager-load the nodes that are connected to
// the "appUserTemplates" edge. The optional arguments are used to configure the query builder of the edge.
func (auq *AsUserQuery) ThenAppUserTemplates(opts ...func(*AsMarketAppUserTemplateQuery)) *AsUserQuery {
	query := &AsMarketAppUserTemplateQuery{config: auq.config}
	for _, opt := range opts {
		opt(query.Where(asmarketappusertemplate.IsDeleted(0)))
	}
	auq.withAppUserTemplates = query
	return auq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantCode string `json:"tenantCode"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AsUser.Query().
//		GroupBy(asuser.FieldTenantCode).
//		Aggregate(schema.Count()).
//		Scan(ctx, &v)
//
func (auq *AsUserQuery) GroupBy(field string, fields ...string) *AsUserGroupBy {
	group := &AsUserGroupBy{config: auq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := auq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return auq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantCode string `json:"tenantCode"`
//	}
//
//	client.AsUser.Query().
//		Select(asuser.FieldTenantCode).
//		Scan(ctx, &v)
//
func (auq *AsUserQuery) Select(fields ...string) *AsUserSelect {
	auq.fields = append(auq.fields, fields...)
	return &AsUserSelect{AsUserQuery: auq}
}

func (auq *AsUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range auq.fields {
		if !asuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("schema: invalid field %q for query", f)}
		}
	}
	if auq.path != nil {
		prev, err := auq.path(ctx)
		if err != nil {
			return err
		}
		auq.sql = prev
	}
	return nil
}

func (auq *AsUserQuery) sqlAll(ctx context.Context) ([]*AsUser, error) {
	var (
		nodes       = []*AsUser{}
		_spec       = auq.querySpec()
		loadedTypes = [9]bool{
			auq.withPerson != nil,
			auq.withRoles != nil,
			auq.withJobs != nil,
			auq.withUsedapps != nil,
			auq.withWorkingDatas != nil,
			auq.withAgencys != nil,
			auq.withRoleDistribs != nil,
			auq.withAppMenusUserSorts != nil,
			auq.withAppUserTemplates != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AsUser{config: auq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("schema: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, auq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := auq.withPerson; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int64]*AsUser)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.Where(predicate.AsPerson(func(s *sql.Selector) {
			s.Where(sql.InValues(asuser.PersonColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.UserID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Person = n
		}
	}

	if query := auq.withRoles; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int64]*AsUser, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Roles = []*AsRole{}
		}
		var (
			edgeids []int64
			edges   = make(map[int64][]*AsUser)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: false,
				Table:   asuser.RolesTable,
				Columns: asuser.RolesPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(asuser.RolesPrimaryKey[0], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := eout.Int64
				inValue := ein.Int64
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, auq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "roles": %w`, err)
		}
		query.Where(asrole.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "roles" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Roles = append(nodes[i].Edges.Roles, n)
			}
		}
	}

	if query := auq.withJobs; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int64]*AsUser, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Jobs = []*AsJob{}
		}
		var (
			edgeids []int64
			edges   = make(map[int64][]*AsUser)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: false,
				Table:   asuser.JobsTable,
				Columns: asuser.JobsPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(asuser.JobsPrimaryKey[0], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := eout.Int64
				inValue := ein.Int64
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, auq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "jobs": %w`, err)
		}
		query.Where(asjob.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "jobs" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Jobs = append(nodes[i].Edges.Jobs, n)
			}
		}
	}

	if query := auq.withUsedapps; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int64]*AsUser)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Usedapps = []*AsMarketUsedApp{}
		}
		query.Where(predicate.AsMarketUsedApp(func(s *sql.Selector) {
			s.Where(sql.InValues(asuser.UsedappsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.AppID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "app_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Usedapps = append(node.Edges.Usedapps, n)
		}
	}

	if query := auq.withWorkingDatas; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int64]*AsUser)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.WorkingDatas = []*AsWorkingData{}
		}
		query.Where(predicate.AsWorkingData(func(s *sql.Selector) {
			s.Where(sql.InValues(asuser.WorkingDatasColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.UserID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.WorkingDatas = append(node.Edges.WorkingDatas, n)
		}
	}

	if query := auq.withAgencys; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int64]*AsUser, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Agencys = []*AsInnerAgency{}
		}
		var (
			edgeids []int64
			edges   = make(map[int64][]*AsUser)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   asuser.AgencysTable,
				Columns: asuser.AgencysPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(asuser.AgencysPrimaryKey[1], fks...))
			},
			ScanValues: func() [2]interface{} {
				return [2]interface{}{new(sql.NullInt64), new(sql.NullInt64)}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := eout.Int64
				inValue := ein.Int64
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				if _, ok := edges[inValue]; !ok {
					edgeids = append(edgeids, inValue)
				}
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, auq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "agencys": %w`, err)
		}
		query.Where(asinneragency.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "agencys" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Agencys = append(nodes[i].Edges.Agencys, n)
			}
		}
	}

	if query := auq.withRoleDistribs; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int64]*AsUser)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.RoleDistribs = []*AsMarketRoleDistribution{}
		}
		query.Where(predicate.AsMarketRoleDistribution(func(s *sql.Selector) {
			s.Where(sql.InValues(asuser.RoleDistribsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.UserID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.RoleDistribs = append(node.Edges.RoleDistribs, n)
		}
	}

	if query := auq.withAppMenusUserSorts; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int64]*AsUser)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.AppMenusUserSorts = []*AsMarketMenuUserSort{}
		}
		query.Where(predicate.AsMarketMenuUserSort(func(s *sql.Selector) {
			s.Where(sql.InValues(asuser.AppMenusUserSortsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.UserID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.AppMenusUserSorts = append(node.Edges.AppMenusUserSorts, n)
		}
	}

	if query := auq.withAppUserTemplates; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int64]*AsUser)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.AppUserTemplates = []*AsMarketAppUserTemplate{}
		}
		query.Where(predicate.AsMarketAppUserTemplate(func(s *sql.Selector) {
			s.Where(sql.InValues(asuser.AppUserTemplatesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.UserID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.AppUserTemplates = append(node.Edges.AppUserTemplates, n)
		}
	}

	return nodes, nil
}

func (auq *AsUserQuery) sqlCount(ctx context.Context) (int64, error) {
	_spec := auq.querySpec()
	_spec.Node.Columns = auq.fields
	if len(auq.fields) > 0 {
		_spec.Unique = auq.unique != nil && *auq.unique
	}
	c, err := sqlgraph.CountNodes(ctx, auq.driver, _spec)
	return int64(c), err
}

func (auq *AsUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := auq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("schema: check existence: %w", err)
	}
	return n > 0, nil
}

func (auq *AsUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   asuser.Table,
			Columns: asuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: asuser.FieldID,
			},
		},
		From:   auq.sql,
		Unique: true,
	}
	if unique := auq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := auq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asuser.FieldID)
		for i := range fields {
			if fields[i] != asuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := auq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := auq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := auq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := auq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (auq *AsUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(auq.driver.Dialect())
	t1 := builder.Table(asuser.Table)
	columns := auq.fields
	if len(columns) == 0 {
		columns = asuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if auq.sql != nil {
		selector = auq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if auq.unique != nil && *auq.unique {
		selector.Distinct()
	}
	for _, p := range auq.predicates {
		p(selector)
	}
	for _, p := range auq.order {
		p(selector)
	}
	if offset := auq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := auq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AsUserGroupBy is the group-by builder for AsUser entities.
type AsUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (augb *AsUserGroupBy) Aggregate(fns ...AggregateFunc) *AsUserGroupBy {
	augb.fns = append(augb.fns, fns...)
	return augb
}

// Scan applies the group-by query and scans the result into the given value.
func (augb *AsUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := augb.path(ctx)
	if err != nil {
		return err
	}
	augb.sql = query
	return augb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (augb *AsUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := augb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(augb.fields) > 1 {
		return nil, errors.New("schema: AsUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := augb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (augb *AsUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := augb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = augb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (augb *AsUserGroupBy) StringX(ctx context.Context) string {
	v, err := augb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(augb.fields) > 1 {
		return nil, errors.New("schema: AsUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := augb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (augb *AsUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := augb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = augb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (augb *AsUserGroupBy) IntX(ctx context.Context) int {
	v, err := augb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(augb.fields) > 1 {
		return nil, errors.New("schema: AsUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := augb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (augb *AsUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := augb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = augb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (augb *AsUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := augb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(augb.fields) > 1 {
		return nil, errors.New("schema: AsUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := augb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (augb *AsUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := augb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = augb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (augb *AsUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := augb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int64s returns list of int64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Int64s(ctx context.Context) ([]int64, error) {
	if len(augb.fields) > 1 {
		return nil, errors.New("schema: AsUserGroupBy.Int64s is not achievable when grouping more than 1 field")
	}
	var v []int64
	if err := augb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Int64sX is like Int64s, but panics if an error occurs.
func (augb *AsUserGroupBy) Int64sX(ctx context.Context) []int64 {
	v, err := augb.Int64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int64 returns a single int64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (augb *AsUserGroupBy) Int64(ctx context.Context) (_ int64, err error) {
	var v []int64
	if v, err = augb.Int64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserGroupBy.Int64s returned %d results when one was expected", len(v))
	}
	return
}

// Int64X is like Int64, but panics if an error occurs.
func (augb *AsUserGroupBy) Int64X(ctx context.Context) int64 {
	v, err := augb.Int64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (augb *AsUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range augb.fields {
		if !asuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := augb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := augb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (augb *AsUserGroupBy) sqlQuery() *sql.Selector {
	selector := augb.sql.Select()
	aggregation := make([]string, 0, len(augb.fns))
	for _, fn := range augb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(augb.fields)+len(augb.fns))
		for _, f := range augb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(augb.fields...)...)
}

// AsUserSelect is the builder for selecting fields of AsUser entities.
type AsUserSelect struct {
	*AsUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aus *AsUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := aus.prepareQuery(ctx); err != nil {
		return err
	}
	aus.sql = aus.AsUserQuery.sqlQuery(ctx)
	return aus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aus *AsUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := aus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(aus.fields) > 1 {
		return nil, errors.New("schema: AsUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := aus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aus *AsUserSelect) StringsX(ctx context.Context) []string {
	v, err := aus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aus *AsUserSelect) StringX(ctx context.Context) string {
	v, err := aus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(aus.fields) > 1 {
		return nil, errors.New("schema: AsUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := aus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aus *AsUserSelect) IntsX(ctx context.Context) []int {
	v, err := aus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aus *AsUserSelect) IntX(ctx context.Context) int {
	v, err := aus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(aus.fields) > 1 {
		return nil, errors.New("schema: AsUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := aus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aus *AsUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := aus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aus *AsUserSelect) Float64X(ctx context.Context) float64 {
	v, err := aus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(aus.fields) > 1 {
		return nil, errors.New("schema: AsUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := aus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aus *AsUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := aus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aus *AsUserSelect) BoolX(ctx context.Context) bool {
	v, err := aus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int64s returns list of int64s from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Int64s(ctx context.Context) ([]int64, error) {
	if len(aus.fields) > 1 {
		return nil, errors.New("schema: AsUserSelect.Int64s is not achievable when selecting more than 1 field")
	}
	var v []int64
	if err := aus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Int64sX is like Int64s, but panics if an error occurs.
func (aus *AsUserSelect) Int64sX(ctx context.Context) []int64 {
	v, err := aus.Int64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int64 returns a single int64 from a selector. It is only allowed when selecting one field.
func (aus *AsUserSelect) Int64(ctx context.Context) (_ int64, err error) {
	var v []int64
	if v, err = aus.Int64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{asuser.Label}
	default:
		err = fmt.Errorf("schema: AsUserSelect.Int64s returned %d results when one was expected", len(v))
	}
	return
}

// Int64X is like Int64, but panics if an error occurs.
func (aus *AsUserSelect) Int64X(ctx context.Context) int64 {
	v, err := aus.Int64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aus *AsUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aus.sql.Query()
	if err := aus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
