// Code generated by goctl. DO NOT EDIT!

package entitys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	actFoFormResourceFieldNames          = builder.RawFieldNames(&ActFoFormResource{})
	actFoFormResourceRows                = strings.Join(actFoFormResourceFieldNames, ",")
	actFoFormResourceRowsExpectAutoSet   = strings.Join(stringx.Remove(actFoFormResourceFieldNames, "`create_time`", "`update_time`"), ",")
	actFoFormResourceRowsWithPlaceHolder = strings.Join(stringx.Remove(actFoFormResourceFieldNames, "`ID_`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheAssetActFoFormResourceIDPrefix = "cache:asset:actFoFormResource:iD:"
)

type (
	actFoFormResourceModel interface {
		Insert(ctx context.Context, data *ActFoFormResource) (sql.Result, error)
		FindOne(ctx context.Context, iD string) (*ActFoFormResource, error)
		Update(ctx context.Context, data *ActFoFormResource) error
		Delete(ctx context.Context, iD string) error
	}

	defaultActFoFormResourceModel struct {
		sqlc.CachedConn
		table string
	}

	ActFoFormResource struct {
		ID            string         `db:"ID_"`
		NAME          sql.NullString `db:"NAME_"`
		DEPLOYMENTID  sql.NullString `db:"DEPLOYMENT_ID_"`
		RESOURCEBYTES sql.NullString `db:"RESOURCE_BYTES_"`
	}
)

func newActFoFormResourceModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultActFoFormResourceModel {
	return &defaultActFoFormResourceModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`act_fo_form_resource`",
	}
}

func (m *defaultActFoFormResourceModel) Insert(ctx context.Context, data *ActFoFormResource) (sql.Result, error) {
	assetActFoFormResourceIDKey := fmt.Sprintf("%s%v", cacheAssetActFoFormResourceIDPrefix, data.ID)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, actFoFormResourceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ID, data.NAME, data.DEPLOYMENTID, data.RESOURCEBYTES)
	}, assetActFoFormResourceIDKey)
	return ret, err
}

func (m *defaultActFoFormResourceModel) FindOne(ctx context.Context, iD string) (*ActFoFormResource, error) {
	assetActFoFormResourceIDKey := fmt.Sprintf("%s%v", cacheAssetActFoFormResourceIDPrefix, iD)
	var resp ActFoFormResource
	err := m.QueryRowCtx(ctx, &resp, assetActFoFormResourceIDKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `ID_` = ? limit 1", actFoFormResourceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, iD)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActFoFormResourceModel) Update(ctx context.Context, data *ActFoFormResource) error {
	assetActFoFormResourceIDKey := fmt.Sprintf("%s%v", cacheAssetActFoFormResourceIDPrefix, data.ID)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `ID_` = ?", m.table, actFoFormResourceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.NAME, data.DEPLOYMENTID, data.RESOURCEBYTES, data.ID)
	}, assetActFoFormResourceIDKey)
	return err
}

func (m *defaultActFoFormResourceModel) Delete(ctx context.Context, iD string) error {
	assetActFoFormResourceIDKey := fmt.Sprintf("%s%v", cacheAssetActFoFormResourceIDPrefix, iD)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `ID_` = ?", m.table)
		return conn.ExecCtx(ctx, query, iD)
	}, assetActFoFormResourceIDKey)
	return err
}

func (m *defaultActFoFormResourceModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAssetActFoFormResourceIDPrefix, primary)
}

func (m *defaultActFoFormResourceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `ID_` = ? limit 1", actFoFormResourceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultActFoFormResourceModel) tableName() string {
	return m.table
}
