// Code generated by goctl. DO NOT EDIT!

package entitys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	actReDeploymentFieldNames          = builder.RawFieldNames(&ActReDeployment{})
	actReDeploymentRows                = strings.Join(actReDeploymentFieldNames, ",")
	actReDeploymentRowsExpectAutoSet   = strings.Join(stringx.Remove(actReDeploymentFieldNames, "`create_time`", "`update_time`"), ",")
	actReDeploymentRowsWithPlaceHolder = strings.Join(stringx.Remove(actReDeploymentFieldNames, "`ID_`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheAssetActReDeploymentIDPrefix = "cache:asset:actReDeployment:iD:"
)

type (
	actReDeploymentModel interface {
		Insert(ctx context.Context, data *ActReDeployment) (sql.Result, error)
		FindOne(ctx context.Context, iD string) (*ActReDeployment, error)
		Update(ctx context.Context, data *ActReDeployment) error
		Delete(ctx context.Context, iD string) error
	}

	defaultActReDeploymentModel struct {
		sqlc.CachedConn
		table string
	}

	ActReDeployment struct {
		ID                 string         `db:"ID_"`
		NAME               sql.NullString `db:"NAME_"`
		CATEGORY           sql.NullString `db:"CATEGORY_"`
		KEY                sql.NullString `db:"KEY_"`
		TENANTID           string         `db:"TENANT_ID_"`
		DEPLOYTIME         sql.NullTime   `db:"DEPLOY_TIME_"`
		DERIVEDFROM        sql.NullString `db:"DERIVED_FROM_"`
		DERIVEDFROMROOT    sql.NullString `db:"DERIVED_FROM_ROOT_"`
		PARENTDEPLOYMENTID sql.NullString `db:"PARENT_DEPLOYMENT_ID_"`
		ENGINEVERSION      sql.NullString `db:"ENGINE_VERSION_"`
	}
)

func newActReDeploymentModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultActReDeploymentModel {
	return &defaultActReDeploymentModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`act_re_deployment`",
	}
}

func (m *defaultActReDeploymentModel) Insert(ctx context.Context, data *ActReDeployment) (sql.Result, error) {
	assetActReDeploymentIDKey := fmt.Sprintf("%s%v", cacheAssetActReDeploymentIDPrefix, data.ID)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, actReDeploymentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ID, data.NAME, data.CATEGORY, data.KEY, data.TENANTID, data.DEPLOYTIME, data.DERIVEDFROM, data.DERIVEDFROMROOT, data.PARENTDEPLOYMENTID, data.ENGINEVERSION)
	}, assetActReDeploymentIDKey)
	return ret, err
}

func (m *defaultActReDeploymentModel) FindOne(ctx context.Context, iD string) (*ActReDeployment, error) {
	assetActReDeploymentIDKey := fmt.Sprintf("%s%v", cacheAssetActReDeploymentIDPrefix, iD)
	var resp ActReDeployment
	err := m.QueryRowCtx(ctx, &resp, assetActReDeploymentIDKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `ID_` = ? limit 1", actReDeploymentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, iD)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActReDeploymentModel) Update(ctx context.Context, data *ActReDeployment) error {
	assetActReDeploymentIDKey := fmt.Sprintf("%s%v", cacheAssetActReDeploymentIDPrefix, data.ID)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `ID_` = ?", m.table, actReDeploymentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.NAME, data.CATEGORY, data.KEY, data.TENANTID, data.DEPLOYTIME, data.DERIVEDFROM, data.DERIVEDFROMROOT, data.PARENTDEPLOYMENTID, data.ENGINEVERSION, data.ID)
	}, assetActReDeploymentIDKey)
	return err
}

func (m *defaultActReDeploymentModel) Delete(ctx context.Context, iD string) error {
	assetActReDeploymentIDKey := fmt.Sprintf("%s%v", cacheAssetActReDeploymentIDPrefix, iD)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `ID_` = ?", m.table)
		return conn.ExecCtx(ctx, query, iD)
	}, assetActReDeploymentIDKey)
	return err
}

func (m *defaultActReDeploymentModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAssetActReDeploymentIDPrefix, primary)
}

func (m *defaultActReDeploymentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `ID_` = ? limit 1", actReDeploymentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultActReDeploymentModel) tableName() string {
	return m.table
}
