// Code generated by goctl. DO NOT EDIT!

package entitys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	asAgencyPersonFieldNames          = builder.RawFieldNames(&AsAgencyPerson{})
	asAgencyPersonRows                = strings.Join(asAgencyPersonFieldNames, ",")
	asAgencyPersonRowsExpectAutoSet   = strings.Join(stringx.Remove(asAgencyPersonFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	asAgencyPersonRowsWithPlaceHolder = strings.Join(stringx.Remove(asAgencyPersonFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheAssetAsAgencyPersonIdPrefix = "cache:asset:asAgencyPerson:id:"
)

type (
	asAgencyPersonModel interface {
		Insert(ctx context.Context, data *AsAgencyPerson) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AsAgencyPerson, error)
		Update(ctx context.Context, data *AsAgencyPerson) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAsAgencyPersonModel struct {
		sqlc.CachedConn
		table string
	}

	AsAgencyPerson struct {
		AgencyId sql.NullInt64 `db:"agency_id"` // 部门id
		PersonId sql.NullInt64 `db:"person_id"` // 人员id
		Id       int64         `db:"id"`
	}
)

func newAsAgencyPersonModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAsAgencyPersonModel {
	return &defaultAsAgencyPersonModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`as_agency_person`",
	}
}

func (m *defaultAsAgencyPersonModel) Insert(ctx context.Context, data *AsAgencyPerson) (sql.Result, error) {
	assetAsAgencyPersonIdKey := fmt.Sprintf("%s%v", cacheAssetAsAgencyPersonIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, asAgencyPersonRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AgencyId, data.PersonId)
	}, assetAsAgencyPersonIdKey)
	return ret, err
}

func (m *defaultAsAgencyPersonModel) FindOne(ctx context.Context, id int64) (*AsAgencyPerson, error) {
	assetAsAgencyPersonIdKey := fmt.Sprintf("%s%v", cacheAssetAsAgencyPersonIdPrefix, id)
	var resp AsAgencyPerson
	err := m.QueryRowCtx(ctx, &resp, assetAsAgencyPersonIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", asAgencyPersonRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAsAgencyPersonModel) Update(ctx context.Context, data *AsAgencyPerson) error {
	assetAsAgencyPersonIdKey := fmt.Sprintf("%s%v", cacheAssetAsAgencyPersonIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, asAgencyPersonRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.AgencyId, data.PersonId, data.Id)
	}, assetAsAgencyPersonIdKey)
	return err
}

func (m *defaultAsAgencyPersonModel) Delete(ctx context.Context, id int64) error {
	assetAsAgencyPersonIdKey := fmt.Sprintf("%s%v", cacheAssetAsAgencyPersonIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, assetAsAgencyPersonIdKey)
	return err
}

func (m *defaultAsAgencyPersonModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAssetAsAgencyPersonIdPrefix, primary)
}

func (m *defaultAsAgencyPersonModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", asAgencyPersonRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAsAgencyPersonModel) tableName() string {
	return m.table
}
