// Code generated by goctl. DO NOT EDIT!

package entitys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	asDatabaseParamMappingFieldNames          = builder.RawFieldNames(&AsDatabaseParamMapping{})
	asDatabaseParamMappingRows                = strings.Join(asDatabaseParamMappingFieldNames, ",")
	asDatabaseParamMappingRowsExpectAutoSet   = strings.Join(stringx.Remove(asDatabaseParamMappingFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	asDatabaseParamMappingRowsWithPlaceHolder = strings.Join(stringx.Remove(asDatabaseParamMappingFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheAssetAsDatabaseParamMappingIdPrefix = "cache:asset:asDatabaseParamMapping:id:"
)

type (
	asDatabaseParamMappingModel interface {
		Insert(ctx context.Context, data *AsDatabaseParamMapping) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AsDatabaseParamMapping, error)
		Update(ctx context.Context, data *AsDatabaseParamMapping) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAsDatabaseParamMappingModel struct {
		sqlc.CachedConn
		table string
	}

	AsDatabaseParamMapping struct {
		Id                    int64          `db:"id"`                       // id
		DataBaseSourceId      string         `db:"data_base_source_id"`      // 数据库源id
		RemoteUserId          sql.NullString `db:"remote_user_id"`           // 远程用户id
		RemoteUserName        sql.NullString `db:"remote_user_name"`         // 远程用户姓名
		RemoteUserAccount     sql.NullString `db:"remote_user_account"`      // 远程用户登录账号
		RemoteUserPhoneNumber sql.NullString `db:"remote_user_phone_number"` // 远程用户手机号码
		RemoteUserExtension   sql.NullString `db:"remote_user_extension"`    // 远程用户扩展属性
		RemoteUserUnitId      sql.NullString `db:"remote_user_unit_id"`      // 远程用户所属部门id
		RemoteUnitId          sql.NullString `db:"remote_unit_id"`           // 远程部门id
		RemoteUnitName        sql.NullString `db:"remote_unit_name"`         // 远程部门名称
		RemoteParentUnitId    sql.NullString `db:"remote_parent_unit_id"`    // 远程部门父节点id
		AddTime               time.Time      `db:"add_time"`                 // 添加时间
		IsDeleted             int64          `db:"is_deleted"`               // 是否已删除
	}
)

func newAsDatabaseParamMappingModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAsDatabaseParamMappingModel {
	return &defaultAsDatabaseParamMappingModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`as_database_param_mapping`",
	}
}

func (m *defaultAsDatabaseParamMappingModel) Insert(ctx context.Context, data *AsDatabaseParamMapping) (sql.Result, error) {
	assetAsDatabaseParamMappingIdKey := fmt.Sprintf("%s%v", cacheAssetAsDatabaseParamMappingIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, asDatabaseParamMappingRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DataBaseSourceId, data.RemoteUserId, data.RemoteUserName, data.RemoteUserAccount, data.RemoteUserPhoneNumber, data.RemoteUserExtension, data.RemoteUserUnitId, data.RemoteUnitId, data.RemoteUnitName, data.RemoteParentUnitId, data.AddTime, data.IsDeleted)
	}, assetAsDatabaseParamMappingIdKey)
	return ret, err
}

func (m *defaultAsDatabaseParamMappingModel) FindOne(ctx context.Context, id int64) (*AsDatabaseParamMapping, error) {
	assetAsDatabaseParamMappingIdKey := fmt.Sprintf("%s%v", cacheAssetAsDatabaseParamMappingIdPrefix, id)
	var resp AsDatabaseParamMapping
	err := m.QueryRowCtx(ctx, &resp, assetAsDatabaseParamMappingIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", asDatabaseParamMappingRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAsDatabaseParamMappingModel) Update(ctx context.Context, data *AsDatabaseParamMapping) error {
	assetAsDatabaseParamMappingIdKey := fmt.Sprintf("%s%v", cacheAssetAsDatabaseParamMappingIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, asDatabaseParamMappingRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DataBaseSourceId, data.RemoteUserId, data.RemoteUserName, data.RemoteUserAccount, data.RemoteUserPhoneNumber, data.RemoteUserExtension, data.RemoteUserUnitId, data.RemoteUnitId, data.RemoteUnitName, data.RemoteParentUnitId, data.AddTime, data.IsDeleted, data.Id)
	}, assetAsDatabaseParamMappingIdKey)
	return err
}

func (m *defaultAsDatabaseParamMappingModel) Delete(ctx context.Context, id int64) error {
	assetAsDatabaseParamMappingIdKey := fmt.Sprintf("%s%v", cacheAssetAsDatabaseParamMappingIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, assetAsDatabaseParamMappingIdKey)
	return err
}

func (m *defaultAsDatabaseParamMappingModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAssetAsDatabaseParamMappingIdPrefix, primary)
}

func (m *defaultAsDatabaseParamMappingModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", asDatabaseParamMappingRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAsDatabaseParamMappingModel) tableName() string {
	return m.table
}
