// Code generated by entc, DO NOT EDIT.

package asmarketmenuusersort

import (
	"orginone/common/tools/date"
)

const (
	// Label holds the string label denoting the asmarketmenuusersort type in the database.
	Label = "as_market_menu_user_sort"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldMenuID holds the string denoting the menu_id field in the database.
	FieldMenuID = "menu_id"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreateUser holds the string denoting the create_user field in the database.
	FieldCreateUser = "create_user"
	// FieldUpdateUser holds the string denoting the update_user field in the database.
	FieldUpdateUser = "update_user"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// EdgeUserx holds the string denoting the userx edge name in mutations.
	EdgeUserx = "userx"
	// EdgeAppmenux holds the string denoting the appmenux edge name in mutations.
	EdgeAppmenux = "appmenux"
	// Table holds the table name of the asmarketmenuusersort in the database.
	Table = "as_market_menu_user_sort"
	// UserxTable is the table that holds the userx relation/edge.
	UserxTable = "as_market_menu_user_sort"
	// UserxInverseTable is the table name for the AsUser entity.
	// It exists in this package in order to avoid circular dependency with the "asuser" package.
	UserxInverseTable = "as_user"
	// UserxColumn is the table column denoting the userx relation/edge.
	UserxColumn = "user_id"
	// AppmenuxTable is the table that holds the appmenux relation/edge.
	AppmenuxTable = "as_market_menu_user_sort"
	// AppmenuxInverseTable is the table name for the AsMarketMenu entity.
	// It exists in this package in order to avoid circular dependency with the "asmarketmenu" package.
	AppmenuxInverseTable = "as_market_menu"
	// AppmenuxColumn is the table column denoting the appmenux relation/edge.
	AppmenuxColumn = "menu_id"
)

// Columns holds all SQL columns for asmarketmenuusersort fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldMenuID,
	FieldSort,
	FieldIsDeleted,
	FieldStatus,
	FieldCreateUser,
	FieldUpdateUser,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int64
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int64
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() date.DateTime
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() date.DateTime
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() date.DateTime
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() int64
)
